Description of combine
Home > iit > combine.m
combine
PURPOSE
SYNOPSIS
function ab = combine(a,b)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
make_title_fb
plot_REP op_min = options(9);
plot_phi
SOURCE CODE
function ab = combine(a,b)
ab = [a b];
ab = sort(ab);
end