Description of L1norm
Home > iit > L1norm.m
L1norm
PURPOSE
% compute distance based on L1 norm divided by two to approximate the earth movers
SYNOPSIS
function D = L1norm(prob,prob2)
DESCRIPTION
% compute distance based on L1 norm divided by two to approximate the earth movers
 prob,prob2 : Two distributions
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
MIP_search_reentry %
phi_comp_bORf Larissa: for smart purviews, op_context is assumed 0, op_min is assumed
phi_comp_bf compute small phi of a given purview...?
SOURCE CODE
function D = L1norm(prob,prob2)
%% compute distance based on L1 norm divided by two to approximate the earth movers
% prob,prob2 : Two distributions
if min(min(prob),min(prob2)) < 0
    warning('Either or both distributions contain negative values');
end
if (length(prob)~= length(prob2))
    warning('Distributions do not have the same support');
end
D = sum(abs(prob - prob2))/2;
if D < 1e-15
    D = 0;
end