Description of mod_mat2str
Home > iit > mod_mat2str.m
mod_mat2str
PURPOSE
SYNOPSIS
function x_s = mod_mat2str(x)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
MIP_search_reentry %
big_phi_all compute Big-phi in every possible subset
big_phi_comp_fb % compute big phi for a subset, subsystem
complex_search % Find complex
conceptscatter3D2D BASED ON GPLOTMATRIX
iit_explorer IIT_EXPLORER MATLAB code for iit_explorer.fig
make_title op_fb = 0 (forward) ,1(backward), 3(both)
make_title_fb
plot_REP op_min = options(9);
plot_partition_bar function plot_partition_bar(Big_phi, REP_cell,phi,MIP_cell, M, plot_panel)
SOURCE CODE
function x_s = mod_mat2str(x)
N = length(x);
if N == 0
    x_s = '[]';
elseif N == 1
    x_s = ['[' int2str(x) ']'];
else
    x_s = mat2str(x);
end