Description of pick_rest
Home > iit > pick_rest.m
pick_rest
PURPOSE
This function finds the complement of a M1 where M is the full set
SYNOPSIS
function M2 = pick_rest(M,M1)
DESCRIPTION
 This function finds the complement of a M1 where M is the full set
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
MIP_search_reentry %
complex_search % Find complex
iit_explorer IIT_EXPLORER MATLAB code for iit_explorer.fig
make_title op_fb = 0 (forward) ,1(backward), 3(both)
partial_prob_comp compute the conditional probability p(x0_b | x1_b)
phi_comp_ex % compute small phi for a purview
phi_comp_ex_unidir pf_tag is 1 for past and 2 for future
plot_PHI_Cut_concepts
rewrap_data
SOURCE CODE
function M2 = pick_rest(M,M1)
% This function finds the complement of a M1 where M is the full set
M2 = M;
for i=1: length(M1)
    M2(M2==M1(i)) = [];
end