Description of subsystem2index
Home > iit > subsystem2index.m
subsystem2index
PURPOSE
SYNOPSIS
function index = subsystem2index(subsystem)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
MIP_search_reentry %
phi_comp_bORf Larissa: for smart purviews, op_context is assumed 0, op_min is assumed
phi_comp_bf compute small phi of a given purview...?
plot_PHI_Cut_concepts
rewrap_data
SOURCE CODE
function index = subsystem2index(subsystem)
N = length(subsystem);
index = 0;
for i = 1:N
    j = subsystem(i);
    index = index + 2^(j-1);
end
end