Description of trans10
Home > iit > trans10.m
trans10
PURPOSE
SYNOPSIS
function x = trans10(sigma)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
expand_prob
expand_prob_general
iit_explorer IIT_EXPLORER MATLAB code for iit_explorer.fig
permute_stateXnode_tpm
prob_prod_comp COMPUTES THE DISTRIBUTION OVER THE STATES OF THE WHOLE SET GIVEN THE DISTRIBUTIONS OF
trans_M M is a subset
SOURCE CODE
function x = trans10(sigma)
N = length(sigma);
% if nargin < 2
    two_pow = 2 .^ (0:N-1)';
%     two_pow = two_pow';
%     two_pow = zeros(N,1);
%     for i=1: N
%         two_pow(i) = 2^(i-1);
%     end
% end
% x = 1;
% for i=1: N
%     x = x + 2^(i-1)*sigma(i);
% end
x = 1 + sum(two_pow.*sigma);