Description of trans2
Home > iit > trans2.m
trans2
PURPOSE
TRANS2(VALUE,LENGTH) returns an array of LENGTH 0's and 1's, representing
SYNOPSIS
function [binary] = trans2(value,length)
DESCRIPTION
 TRANS2(VALUE,LENGTH) returns an array of LENGTH 0's and 1's, representing
   the binary number equal to VALUE
   This function also comes as compiled MEX files, the m-file here is a
   backup if the current
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
cpt_removal_network build a cell array that contains all of the subsets
expand_prob
expand_prob_general
gen_dist_matrix2 generates the distance matrix between vertices which can be used as
iit VERSION v0.04 - 11.14.2012
iit_explorer IIT_EXPLORER MATLAB code for iit_explorer.fig
iit_run IIT_RUN Computes concepts, small and big phi, and partition information
permute_stateXnode_tpm
plot_REP op_min = options(9);
plot_partition_bar function plot_partition_bar(Big_phi, REP_cell,phi,MIP_cell, M, plot_panel)
prob_prod_comp COMPUTES THE DISTRIBUTION OVER THE STATES OF THE WHOLE SET GIVEN THE DISTRIBUTIONS OF
SOURCE CODE
function [binary] = trans2(value,length)
% TRANS2(VALUE,LENGTH) returns an array of LENGTH 0's and 1's, representing
%   the binary number equal to VALUE
%
%   This function also comes as compiled MEX files, the m-file here is a
%   backup if the current
% SHOULD WE FLIPLR RESULT
% this is a case where the for loop seems to be faster, see for yourself...
% tic
% binary = mod(floor(value./(2.^(0:length-1))),2)
% toc
%
% tic
binary = zeros(length,1);
for i = 1:length
    binary(i) = value - 2 * floor(value/2);
    value = floor(value/2);
end
% binary
% toc